name: frontend
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # check for latest version

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/bg.png
    - assets/bg2.png
    - assets/airtemplogo.png
    - assets/watertemplogo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"  # path to your logo image